### PR TITLE
Add patch for use with Python 3.11

### PR DESCRIPTION
**Pull request by chrisburr**
Fixing the issue seen in https://github.com/conda-forge/pytest-feedstock/pull/152

### CODE REVIEW

**Comment by chrisburr** [comment]
There's something weird still going on as it's not looking in `lib/python3.11/lib-dynload` meaning modules like `math` can't be imported...

**Comment by chrisburr** [comment]
My current best guess is that https://github.com/python/cpython/pull/29041/ is the change that has broken crossenv.

**Comment by chrisburr** [comment]
See https://github.com/conda-forge/cross-python-feedstock/pull/57 for the solution.

**Comment by isuruf** [comment]
@chrisburr, please wait for the maintainers to review PRs in the future. Can you add yourself as a maintainer to all the feedstocks you merged today? `crossenv, cross-python, python_abi, python` etc?

**Comment by chrisburr** [comment]
@isuruf sorry about that, I should have been more patient waiting with these.

> Can you add yourself as a maintainer to all the feedstocks you merged today? crossenv, cross-python, python_abi, python etc?

Will do :+1:

**Pull request merged**
